[mongodb]
mongodb.viswak.shop


[catalogue]
catalogue.viswak.shop


[redis]
redis.viswak.shop

[user]
user.viswak.shop

[cart]
cart.viswak.shop

[frontend]
viswak.shop


[mysql]
mysql.viswak.shop
172.31.24.58

[local]
localhost

