- name: Doing the Redis world
  hosts: redis 
  become: yes
  tasks:
  - name: disabling the redis
    ansible.builtin.command: dnf module disable redis -y

  - name: enabling the redis
    ansible.builtin.command: dnf module enable redis:7 -y

  - name: installing the redis
    ansible.builtin.dnf:
      name: redis 
      state: present

  - name: Replace a localhost entry with our own
    ansible.builtin.replace:
      path: /etc/redis/redis.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0 '
    
  - name: Disabling the protective mode 
    ansible.builtin.lineinfile:
      path: /etc/redis/redis.conf
      regexp: 'protected-mode'
      line: protected-mode no
    
  - name: Start and enable redis
    ansible.builtin.service:
      name: redis
      state: started
      enabled: yes
      