- name: Configure shipping
  hosts: shipping
  become: yes
  tasks:
  - name: Installing maven
    ansible.builtin.dnf:
      name: maven
      state: present

  - name: Installing PyMySQL
    ansible.builtin.pip:
      name: PyMySQL
      executable: pip3

  - name: Create application user
    ansible.builtin.user:
      name: roboshop
      home: /app
      shell: /sbin/nologin
      system: true
  
  - name: Create a directory if it does not exist
    ansible.builtin.file:
      path: /app 
      state: directory

  - name: Download configuration file
    ansible.builtin.get_url:
      url: "https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip"
      dest: /tmp/shipping.zip

  - name: Unzipping the code
    ansible.builtin.unarchive:
      src: /tmp/shipping.zip
      dest: /app
      remote_src: yes
  
  - name: Install maven dependencies
    ansible.builtin.command: mvn clean package 
    args:
      chdir: /app

  - name: Renaming name
    ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar 
    args:
      chdir: /app


  - name: Copying the file
    ansible.builtin.copy:
      src: shipping.service
      dest: /etc/systemd/system/shipping.service
      

  - name: Systemctl daemon-reload
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: Start and enable shipping
    ansible.builtin.service:
      name: shipping
      state: started
      enabled: yes

  - name: Installing mysql
    ansible.builtin.dnf:
      name: mysql
      state: present

  - name: connect to mysql using app user
    community.mysql.mysql_info:
      login_user: shipping
      login_password: RoboShop@1
      login_host: mysql.viswak.shop
      login_db: cities

    